// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'7c1efddabdbfb3908796256374a3ab44079c24ca88a9bfbebcb93cb7de96b879'>;
export type ExecutionHash =
  ExecutionHashBase<'751722900074e593a2dbc1ad4c124e7db7289611a17c4f3fbece310a06f63945'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly ActivityEvent: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly leadId: CodecTypes['pg/text@1']['output'];
      readonly payload: CodecTypes['pg/jsonb@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
    };
    readonly Appointment: {
      readonly agentId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly endsAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly leadId: CodecTypes['pg/text@1']['output'];
      readonly startsAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly status: 'BOOKED' | 'CANCELLED' | 'COMPLETED' | 'NO_SHOW';
    };
    readonly Lead: {
      readonly aiEnabled: CodecTypes['pg/bool@1']['output'];
      readonly area: CodecTypes['pg/text@1']['output'] | null;
      readonly assignedToId: CodecTypes['pg/text@1']['output'] | null;
      readonly budgetMax: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly firstResponseAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly intent: 'BUYER' | 'SELLER' | 'INVESTOR' | 'UNKNOWN';
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly preApproved: CodecTypes['pg/bool@1']['output'] | null;
      readonly score: CodecTypes['pg/int4@1']['output'];
      readonly source: 'WEBSITE' | 'FACEBOOK' | 'ZILLOW' | 'GOOGLE_ADS' | 'MANUAL';
      readonly stage:
        'NEW' | 'CONTACTED' | 'QUALIFIED' | 'APPOINTMENT' | 'CLOSED_WON' | 'CLOSED_LOST';
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly temperature: 'HOT' | 'WARM' | 'COLD';
      readonly timelineMonths: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Message: {
      readonly author: 'LEAD' | 'AI' | 'AGENT' | 'SYSTEM';
      readonly body: CodecTypes['pg/text@1']['output'];
      readonly channel: 'WEB' | 'EMAIL' | 'SMS';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly leadId: CodecTypes['pg/text@1']['output'];
      readonly meta: CodecTypes['pg/jsonb@1']['output'] | null;
    };
    readonly Sequence: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly trigger: CodecTypes['pg/text@1']['output'];
    };
    readonly SequenceEnrollment: {
      readonly currentStep: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly leadId: CodecTypes['pg/text@1']['output'];
      readonly sequenceId: CodecTypes['pg/text@1']['output'];
      readonly status: 'ACTIVE' | 'STOPPED' | 'DONE';
    };
    readonly SequenceStep: {
      readonly channel: 'WEB' | 'EMAIL' | 'SMS';
      readonly delayMinutes: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly position: CodecTypes['pg/int4@1']['output'];
      readonly sequenceId: CodecTypes['pg/text@1']['output'];
      readonly template: CodecTypes['pg/text@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'AGENT';
    };
    readonly WebhookEvent: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly idempotencyKey: CodecTypes['pg/text@1']['output'];
      readonly payload: CodecTypes['pg/jsonb@1']['output'];
      readonly receivedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly source: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly ActivityEvent: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly leadId: CodecTypes['pg/text@1']['input'];
      readonly payload: CodecTypes['pg/jsonb@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
    };
    readonly Appointment: {
      readonly agentId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly endsAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly leadId: CodecTypes['pg/text@1']['input'];
      readonly startsAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly status: 'BOOKED' | 'CANCELLED' | 'COMPLETED' | 'NO_SHOW';
    };
    readonly Lead: {
      readonly aiEnabled: CodecTypes['pg/bool@1']['input'];
      readonly area: CodecTypes['pg/text@1']['input'] | null;
      readonly assignedToId: CodecTypes['pg/text@1']['input'] | null;
      readonly budgetMax: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly firstResponseAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly intent: 'BUYER' | 'SELLER' | 'INVESTOR' | 'UNKNOWN';
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly preApproved: CodecTypes['pg/bool@1']['input'] | null;
      readonly score: CodecTypes['pg/int4@1']['input'];
      readonly source: 'WEBSITE' | 'FACEBOOK' | 'ZILLOW' | 'GOOGLE_ADS' | 'MANUAL';
      readonly stage:
        'NEW' | 'CONTACTED' | 'QUALIFIED' | 'APPOINTMENT' | 'CLOSED_WON' | 'CLOSED_LOST';
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly temperature: 'HOT' | 'WARM' | 'COLD';
      readonly timelineMonths: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Message: {
      readonly author: 'LEAD' | 'AI' | 'AGENT' | 'SYSTEM';
      readonly body: CodecTypes['pg/text@1']['input'];
      readonly channel: 'WEB' | 'EMAIL' | 'SMS';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly leadId: CodecTypes['pg/text@1']['input'];
      readonly meta: CodecTypes['pg/jsonb@1']['input'] | null;
    };
    readonly Sequence: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly trigger: CodecTypes['pg/text@1']['input'];
    };
    readonly SequenceEnrollment: {
      readonly currentStep: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly leadId: CodecTypes['pg/text@1']['input'];
      readonly sequenceId: CodecTypes['pg/text@1']['input'];
      readonly status: 'ACTIVE' | 'STOPPED' | 'DONE';
    };
    readonly SequenceStep: {
      readonly channel: 'WEB' | 'EMAIL' | 'SMS';
      readonly delayMinutes: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly position: CodecTypes['pg/int4@1']['input'];
      readonly sequenceId: CodecTypes['pg/text@1']['input'];
      readonly template: CodecTypes['pg/text@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'AGENT';
    };
    readonly WebhookEvent: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly idempotencyKey: CodecTypes['pg/text@1']['input'];
      readonly payload: CodecTypes['pg/jsonb@1']['input'];
      readonly receivedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly source: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly ActivityEvent: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly leadId: CodecTypes['pg/text@1']['output'];
      readonly payload: CodecTypes['pg/jsonb@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
    };
    readonly Appointment: {
      readonly agentId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly endsAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly leadId: CodecTypes['pg/text@1']['output'];
      readonly startsAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly status: 'BOOKED' | 'CANCELLED' | 'COMPLETED' | 'NO_SHOW';
    };
    readonly Lead: {
      readonly aiEnabled: CodecTypes['pg/bool@1']['output'];
      readonly area: CodecTypes['pg/text@1']['output'] | null;
      readonly assignedToId: CodecTypes['pg/text@1']['output'] | null;
      readonly budgetMax: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly firstResponseAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly intent: 'BUYER' | 'SELLER' | 'INVESTOR' | 'UNKNOWN';
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly phone: CodecTypes['pg/text@1']['output'] | null;
      readonly preApproved: CodecTypes['pg/bool@1']['output'] | null;
      readonly score: CodecTypes['pg/int4@1']['output'];
      readonly source: 'WEBSITE' | 'FACEBOOK' | 'ZILLOW' | 'GOOGLE_ADS' | 'MANUAL';
      readonly stage:
        'NEW' | 'CONTACTED' | 'QUALIFIED' | 'APPOINTMENT' | 'CLOSED_WON' | 'CLOSED_LOST';
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly temperature: 'HOT' | 'WARM' | 'COLD';
      readonly timelineMonths: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Message: {
      readonly author: 'LEAD' | 'AI' | 'AGENT' | 'SYSTEM';
      readonly body: CodecTypes['pg/text@1']['output'];
      readonly channel: 'WEB' | 'EMAIL' | 'SMS';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly leadId: CodecTypes['pg/text@1']['output'];
      readonly meta: CodecTypes['pg/jsonb@1']['output'] | null;
    };
    readonly Sequence: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly trigger: CodecTypes['pg/text@1']['output'];
    };
    readonly SequenceEnrollment: {
      readonly currentStep: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly leadId: CodecTypes['pg/text@1']['output'];
      readonly sequenceId: CodecTypes['pg/text@1']['output'];
      readonly status: 'ACTIVE' | 'STOPPED' | 'DONE';
    };
    readonly SequenceStep: {
      readonly channel: 'WEB' | 'EMAIL' | 'SMS';
      readonly delayMinutes: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly position: CodecTypes['pg/int4@1']['output'];
      readonly sequenceId: CodecTypes['pg/text@1']['output'];
      readonly template: CodecTypes['pg/text@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'AGENT';
    };
    readonly WebhookEvent: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly idempotencyKey: CodecTypes['pg/text@1']['output'];
      readonly payload: CodecTypes['pg/jsonb@1']['output'];
      readonly receivedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly source: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly ActivityEvent: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly leadId: CodecTypes['pg/text@1']['input'];
      readonly payload: CodecTypes['pg/jsonb@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
    };
    readonly Appointment: {
      readonly agentId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly endsAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly leadId: CodecTypes['pg/text@1']['input'];
      readonly startsAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly status: 'BOOKED' | 'CANCELLED' | 'COMPLETED' | 'NO_SHOW';
    };
    readonly Lead: {
      readonly aiEnabled: CodecTypes['pg/bool@1']['input'];
      readonly area: CodecTypes['pg/text@1']['input'] | null;
      readonly assignedToId: CodecTypes['pg/text@1']['input'] | null;
      readonly budgetMax: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly firstResponseAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly intent: 'BUYER' | 'SELLER' | 'INVESTOR' | 'UNKNOWN';
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly phone: CodecTypes['pg/text@1']['input'] | null;
      readonly preApproved: CodecTypes['pg/bool@1']['input'] | null;
      readonly score: CodecTypes['pg/int4@1']['input'];
      readonly source: 'WEBSITE' | 'FACEBOOK' | 'ZILLOW' | 'GOOGLE_ADS' | 'MANUAL';
      readonly stage:
        'NEW' | 'CONTACTED' | 'QUALIFIED' | 'APPOINTMENT' | 'CLOSED_WON' | 'CLOSED_LOST';
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly temperature: 'HOT' | 'WARM' | 'COLD';
      readonly timelineMonths: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Message: {
      readonly author: 'LEAD' | 'AI' | 'AGENT' | 'SYSTEM';
      readonly body: CodecTypes['pg/text@1']['input'];
      readonly channel: 'WEB' | 'EMAIL' | 'SMS';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly leadId: CodecTypes['pg/text@1']['input'];
      readonly meta: CodecTypes['pg/jsonb@1']['input'] | null;
    };
    readonly Sequence: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly trigger: CodecTypes['pg/text@1']['input'];
    };
    readonly SequenceEnrollment: {
      readonly currentStep: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly leadId: CodecTypes['pg/text@1']['input'];
      readonly sequenceId: CodecTypes['pg/text@1']['input'];
      readonly status: 'ACTIVE' | 'STOPPED' | 'DONE';
    };
    readonly SequenceStep: {
      readonly channel: 'WEB' | 'EMAIL' | 'SMS';
      readonly delayMinutes: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly position: CodecTypes['pg/int4@1']['input'];
      readonly sequenceId: CodecTypes['pg/text@1']['input'];
      readonly template: CodecTypes['pg/text@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'AGENT';
    };
    readonly WebhookEvent: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly idempotencyKey: CodecTypes['pg/text@1']['input'];
      readonly payload: CodecTypes['pg/jsonb@1']['input'];
      readonly receivedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly source: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_ActivityEvent = {
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    leadId: CodecTypes['pg/text@1']['output'];
    payload: CodecTypes['pg/jsonb@1']['output'];
    type: CodecTypes['pg/text@1']['output'];
    lead: public_Lead;
    readonly [RelationKeys]?: 'lead';
  };
  export type public_Appointment = {
    agentId: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    endsAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    leadId: CodecTypes['pg/text@1']['output'];
    startsAt: CodecTypes['pg/timestamptz-string@1']['output'];
    status: 'BOOKED' | 'CANCELLED' | 'COMPLETED' | 'NO_SHOW';
    agent: public_User;
    lead: public_Lead;
    readonly [RelationKeys]?: 'agent' | 'lead';
  };
  export type public_Lead = {
    aiEnabled: CodecTypes['pg/bool@1']['output'];
    area: CodecTypes['pg/text@1']['output'] | null;
    assignedToId: CodecTypes['pg/text@1']['output'] | null;
    budgetMax: CodecTypes['pg/int4@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    email: CodecTypes['pg/text@1']['output'] | null;
    firstResponseAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    intent: 'BUYER' | 'SELLER' | 'INVESTOR' | 'UNKNOWN';
    name: CodecTypes['pg/text@1']['output'] | null;
    phone: CodecTypes['pg/text@1']['output'] | null;
    preApproved: CodecTypes['pg/bool@1']['output'] | null;
    score: CodecTypes['pg/int4@1']['output'];
    source: 'WEBSITE' | 'FACEBOOK' | 'ZILLOW' | 'GOOGLE_ADS' | 'MANUAL';
    stage: 'NEW' | 'CONTACTED' | 'QUALIFIED' | 'APPOINTMENT' | 'CLOSED_WON' | 'CLOSED_LOST';
    tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    temperature: 'HOT' | 'WARM' | 'COLD';
    timelineMonths: CodecTypes['pg/int4@1']['output'] | null;
    assignedTo: public_User | null;
    readonly [RelationKeys]?: 'assignedTo';
  };
  export type public_Message = {
    author: 'LEAD' | 'AI' | 'AGENT' | 'SYSTEM';
    body: CodecTypes['pg/text@1']['output'];
    channel: 'WEB' | 'EMAIL' | 'SMS';
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    leadId: CodecTypes['pg/text@1']['output'];
    meta: CodecTypes['pg/jsonb@1']['output'] | null;
    lead: public_Lead;
    readonly [RelationKeys]?: 'lead';
  };
  export type public_Sequence = {
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    trigger: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_SequenceEnrollment = {
    currentStep: CodecTypes['pg/int4@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    leadId: CodecTypes['pg/text@1']['output'];
    sequenceId: CodecTypes['pg/text@1']['output'];
    status: 'ACTIVE' | 'STOPPED' | 'DONE';
    lead: public_Lead;
    sequence: public_Sequence;
    readonly [RelationKeys]?: 'lead' | 'sequence';
  };
  export type public_SequenceStep = {
    channel: 'WEB' | 'EMAIL' | 'SMS';
    delayMinutes: CodecTypes['pg/int4@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    position: CodecTypes['pg/int4@1']['output'];
    sequenceId: CodecTypes['pg/text@1']['output'];
    template: CodecTypes['pg/text@1']['output'];
    sequence: public_Sequence;
    readonly [RelationKeys]?: 'sequence';
  };
  export type public_User = {
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    passwordHash: CodecTypes['pg/text@1']['output'];
    role: 'ADMIN' | 'AGENT';
    readonly [RelationKeys]?: never;
  };
  export type public_WebhookEvent = {
    id: CodecTypes['pg/text@1']['output'];
    idempotencyKey: CodecTypes['pg/text@1']['output'];
    payload: CodecTypes['pg/jsonb@1']['output'];
    receivedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    source: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    ActivityEvent: Models.public_ActivityEvent;
    Appointment: Models.public_Appointment;
    Lead: Models.public_Lead;
    Message: Models.public_Message;
    Sequence: Models.public_Sequence;
    SequenceEnrollment: Models.public_SequenceEnrollment;
    SequenceStep: Models.public_SequenceStep;
    User: Models.public_User;
    WebhookEvent: Models.public_WebhookEvent;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly ActivityEvent: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly leadId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'ActivityEvent_leadId_createdAt_idx_634711b6';
                  readonly prefix: 'ActivityEvent_leadId_createdAt_idx';
                  readonly columns: readonly ['leadId', 'createdAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'ActivityEvent_leadId_idx_9113844c';
                  readonly prefix: 'ActivityEvent_leadId_idx';
                  readonly columns: readonly ['leadId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'ActivityEvent_type_createdAt_idx_00d94001';
                  readonly prefix: 'ActivityEvent_type_createdAt_idx';
                  readonly columns: readonly ['type', 'createdAt'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ActivityEvent';
                    readonly columns: readonly ['leadId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Lead';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Appointment: {
              columns: {
                readonly agentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly endsAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly leadId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly startsAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'BOOKED'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Appointment_agentId_idx_8d0ba4f0';
                  readonly prefix: 'Appointment_agentId_idx';
                  readonly columns: readonly ['agentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Appointment_leadId_idx_9113844c';
                  readonly prefix: 'Appointment_leadId_idx';
                  readonly columns: readonly ['leadId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'appointment_agent_slot_booked_d474ab00';
                  readonly prefix: 'appointment_agent_slot_booked';
                  readonly columns: readonly ['agentId', 'startsAt'];
                  readonly where: "status = 'BOOKED'";
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Appointment';
                    readonly columns: readonly ['leadId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Lead';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Appointment';
                    readonly columns: readonly ['agentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Lead: {
              columns: {
                readonly aiEnabled: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly area: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly assignedToId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly budgetMax: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly firstResponseAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly intent: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'UNKNOWN'>;
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly phone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly preApproved: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
                readonly score: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly stage: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'NEW'>;
                  };
                };
                readonly tags: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', readonly []>;
                  };
                };
                readonly temperature: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'COLD'>;
                  };
                };
                readonly timelineMonths: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Lead_assignedToId_idx_45a131c2';
                  readonly prefix: 'Lead_assignedToId_idx';
                  readonly columns: readonly ['assignedToId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Lead_email_idx_46df9cad';
                  readonly prefix: 'Lead_email_idx';
                  readonly columns: readonly ['email'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Lead_phone_idx_8db23f45';
                  readonly prefix: 'Lead_phone_idx';
                  readonly columns: readonly ['phone'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Lead_source_createdAt_idx_ca471564';
                  readonly prefix: 'Lead_source_createdAt_idx';
                  readonly columns: readonly ['source', 'createdAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Lead_stage_idx_51755035';
                  readonly prefix: 'Lead_stage_idx';
                  readonly columns: readonly ['stage'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Lead';
                    readonly columns: readonly ['assignedToId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'User';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Message: {
              columns: {
                readonly author: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly body: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly channel: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly leadId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly meta: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Message_leadId_createdAt_idx_634711b6';
                  readonly prefix: 'Message_leadId_createdAt_idx';
                  readonly columns: readonly ['leadId', 'createdAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Message_leadId_idx_9113844c';
                  readonly prefix: 'Message_leadId_idx';
                  readonly columns: readonly ['leadId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Message';
                    readonly columns: readonly ['leadId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Lead';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Sequence: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly trigger: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['name'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly SequenceEnrollment: {
              columns: {
                readonly currentStep: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly leadId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sequenceId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'ACTIVE'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['leadId', 'sequenceId'] }];
              indexes: readonly [
                {
                  readonly name: 'SequenceEnrollment_leadId_idx_9113844c';
                  readonly prefix: 'SequenceEnrollment_leadId_idx';
                  readonly columns: readonly ['leadId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'SequenceEnrollment_sequenceId_idx_de377412';
                  readonly prefix: 'SequenceEnrollment_sequenceId_idx';
                  readonly columns: readonly ['sequenceId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'SequenceEnrollment';
                    readonly columns: readonly ['leadId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Lead';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'SequenceEnrollment';
                    readonly columns: readonly ['sequenceId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Sequence';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly SequenceStep: {
              columns: {
                readonly channel: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly delayMinutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly position: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly sequenceId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly template: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['sequenceId', 'position'] }];
              indexes: readonly [
                {
                  readonly name: 'SequenceStep_sequenceId_idx_de377412';
                  readonly prefix: 'SequenceStep_sequenceId_idx';
                  readonly columns: readonly ['sequenceId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'SequenceStep';
                    readonly columns: readonly ['sequenceId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Sequence';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly User: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'AGENT'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly WebhookEvent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly idempotencyKey: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly receivedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['idempotencyKey'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly AppointmentStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['BOOKED', 'CANCELLED', 'COMPLETED', 'NO_SHOW'];
            };
            readonly Author: {
              readonly kind: 'valueSet';
              readonly values: readonly ['LEAD', 'AI', 'AGENT', 'SYSTEM'];
            };
            readonly Channel: {
              readonly kind: 'valueSet';
              readonly values: readonly ['WEB', 'EMAIL', 'SMS'];
            };
            readonly EnrollmentStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ACTIVE', 'STOPPED', 'DONE'];
            };
            readonly Intent: {
              readonly kind: 'valueSet';
              readonly values: readonly ['BUYER', 'SELLER', 'INVESTOR', 'UNKNOWN'];
            };
            readonly LeadSource: {
              readonly kind: 'valueSet';
              readonly values: readonly ['WEBSITE', 'FACEBOOK', 'ZILLOW', 'GOOGLE_ADS', 'MANUAL'];
            };
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'AGENT'];
            };
            readonly Stage: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'NEW',
                'CONTACTED',
                'QUALIFIED',
                'APPOINTMENT',
                'CLOSED_WON',
                'CLOSED_LOST',
              ];
            };
            readonly Temperature: {
              readonly kind: 'valueSet';
              readonly values: readonly ['HOT', 'WARM', 'COLD'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly ActivityEvent: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ActivityEvent';
    };
    readonly Appointment: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Appointment';
    };
    readonly Lead: { readonly namespace: 'public' & NamespaceId; readonly model: 'Lead' };
    readonly Message: { readonly namespace: 'public' & NamespaceId; readonly model: 'Message' };
    readonly Sequence: { readonly namespace: 'public' & NamespaceId; readonly model: 'Sequence' };
    readonly SequenceEnrollment: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SequenceEnrollment';
    };
    readonly SequenceStep: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SequenceStep';
    };
    readonly User: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly WebhookEvent: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'WebhookEvent';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly ActivityEvent: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly leadId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly lead: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Lead' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['leadId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ActivityEvent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly leadId: { readonly column: 'leadId' };
                readonly payload: { readonly column: 'payload' };
                readonly type: { readonly column: 'type' };
              };
            };
          };
          readonly Appointment: {
            readonly fields: {
              readonly agentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly endsAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly leadId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startsAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly agent: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['agentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly lead: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Lead' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['leadId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Appointment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly agentId: { readonly column: 'agentId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly endsAt: { readonly column: 'endsAt' };
                readonly id: { readonly column: 'id' };
                readonly leadId: { readonly column: 'leadId' };
                readonly startsAt: { readonly column: 'startsAt' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly Lead: {
            readonly fields: {
              readonly aiEnabled: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly area: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly assignedToId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly budgetMax: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly firstResponseAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly intent: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly preApproved: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly score: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly stage: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tags: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly temperature: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly timelineMonths: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly assignedTo: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['assignedToId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Lead';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly aiEnabled: { readonly column: 'aiEnabled' };
                readonly area: { readonly column: 'area' };
                readonly assignedToId: { readonly column: 'assignedToId' };
                readonly budgetMax: { readonly column: 'budgetMax' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly firstResponseAt: { readonly column: 'firstResponseAt' };
                readonly id: { readonly column: 'id' };
                readonly intent: { readonly column: 'intent' };
                readonly name: { readonly column: 'name' };
                readonly phone: { readonly column: 'phone' };
                readonly preApproved: { readonly column: 'preApproved' };
                readonly score: { readonly column: 'score' };
                readonly source: { readonly column: 'source' };
                readonly stage: { readonly column: 'stage' };
                readonly tags: { readonly column: 'tags' };
                readonly temperature: { readonly column: 'temperature' };
                readonly timelineMonths: { readonly column: 'timelineMonths' };
              };
            };
          };
          readonly Message: {
            readonly fields: {
              readonly author: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly body: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly channel: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly leadId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly meta: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
            };
            readonly relations: {
              readonly lead: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Lead' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['leadId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Message';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly author: { readonly column: 'author' };
                readonly body: { readonly column: 'body' };
                readonly channel: { readonly column: 'channel' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly leadId: { readonly column: 'leadId' };
                readonly meta: { readonly column: 'meta' };
              };
            };
          };
          readonly Sequence: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly trigger: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Sequence';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly trigger: { readonly column: 'trigger' };
              };
            };
          };
          readonly SequenceEnrollment: {
            readonly fields: {
              readonly currentStep: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly leadId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sequenceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly lead: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Lead' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['leadId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly sequence: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Sequence';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['sequenceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'SequenceEnrollment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly currentStep: { readonly column: 'currentStep' };
                readonly id: { readonly column: 'id' };
                readonly leadId: { readonly column: 'leadId' };
                readonly sequenceId: { readonly column: 'sequenceId' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly SequenceStep: {
            readonly fields: {
              readonly channel: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly delayMinutes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly position: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly sequenceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly template: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly sequence: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Sequence';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['sequenceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'SequenceStep';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly channel: { readonly column: 'channel' };
                readonly delayMinutes: { readonly column: 'delayMinutes' };
                readonly id: { readonly column: 'id' };
                readonly position: { readonly column: 'position' };
                readonly sequenceId: { readonly column: 'sequenceId' };
                readonly template: { readonly column: 'template' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'User';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly passwordHash: { readonly column: 'passwordHash' };
                readonly role: { readonly column: 'role' };
              };
            };
          };
          readonly WebhookEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idempotencyKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly receivedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'WebhookEvent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly idempotencyKey: { readonly column: 'idempotencyKey' };
                readonly payload: { readonly column: 'payload' };
                readonly receivedAt: { readonly column: 'receivedAt' };
                readonly source: { readonly column: 'source' };
              };
            };
          };
        };
        readonly enum: {
          readonly AppointmentStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'BOOKED'; readonly value: 'BOOKED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
              { readonly name: 'COMPLETED'; readonly value: 'COMPLETED' },
              { readonly name: 'NO_SHOW'; readonly value: 'NO_SHOW' },
            ];
          };
          readonly Author: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'LEAD'; readonly value: 'LEAD' },
              { readonly name: 'AI'; readonly value: 'AI' },
              { readonly name: 'AGENT'; readonly value: 'AGENT' },
              { readonly name: 'SYSTEM'; readonly value: 'SYSTEM' },
            ];
          };
          readonly Channel: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'WEB'; readonly value: 'WEB' },
              { readonly name: 'EMAIL'; readonly value: 'EMAIL' },
              { readonly name: 'SMS'; readonly value: 'SMS' },
            ];
          };
          readonly EnrollmentStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ACTIVE'; readonly value: 'ACTIVE' },
              { readonly name: 'STOPPED'; readonly value: 'STOPPED' },
              { readonly name: 'DONE'; readonly value: 'DONE' },
            ];
          };
          readonly Intent: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'BUYER'; readonly value: 'BUYER' },
              { readonly name: 'SELLER'; readonly value: 'SELLER' },
              { readonly name: 'INVESTOR'; readonly value: 'INVESTOR' },
              { readonly name: 'UNKNOWN'; readonly value: 'UNKNOWN' },
            ];
          };
          readonly LeadSource: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'WEBSITE'; readonly value: 'WEBSITE' },
              { readonly name: 'FACEBOOK'; readonly value: 'FACEBOOK' },
              { readonly name: 'ZILLOW'; readonly value: 'ZILLOW' },
              { readonly name: 'GOOGLE_ADS'; readonly value: 'GOOGLE_ADS' },
              { readonly name: 'MANUAL'; readonly value: 'MANUAL' },
            ];
          };
          readonly Role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
              { readonly name: 'AGENT'; readonly value: 'AGENT' },
            ];
          };
          readonly Stage: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'NEW'; readonly value: 'NEW' },
              { readonly name: 'CONTACTED'; readonly value: 'CONTACTED' },
              { readonly name: 'QUALIFIED'; readonly value: 'QUALIFIED' },
              { readonly name: 'APPOINTMENT'; readonly value: 'APPOINTMENT' },
              { readonly name: 'CLOSED_WON'; readonly value: 'CLOSED_WON' },
              { readonly name: 'CLOSED_LOST'; readonly value: 'CLOSED_LOST' },
            ];
          };
          readonly Temperature: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'HOT'; readonly value: 'HOT' },
              { readonly name: 'WARM'; readonly value: 'WARM' },
              { readonly name: 'COLD'; readonly value: 'COLD' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'ActivityEvent';
          };
        },
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'Appointment';
          };
        },
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'Lead';
          };
        },
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'Message';
          };
        },
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'Sequence';
          };
        },
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'SequenceEnrollment';
          };
        },
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'SequenceStep';
          };
        },
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'User';
          };
        },
        {
          readonly onCreate: { readonly id: 'cuid2'; readonly kind: 'generator' };
          readonly ref: {
            readonly column: 'id';
            readonly namespace: 'public';
            readonly table: 'WebhookEvent';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
